### ISSUE TITLE
Create Counter Example and Deploy to Mobile Device!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-counter-example#5]
A counter is the "Hello World" of Apps. e.g: https://github.com/dwyl/phoenix-liveview-counter-tutorial
Our mission with this example/tutorial is to create the most basic possible counter in `Flutter` and get it running on a physical mobile device (e.g: one of the "Test" iPhones in the office)

# Todo

+ [x] Update this tutorial to be more beginner-friendly (e.g. add more context and step-by-step instructions)
+ [x] Run the counter on a **_real_ device** (not just the simulator) e.g. plug-in a Test iPhone (we have 2 of them in the office)
+ [x] Take photos/videos of the counter working on the **_real_ device** and upload them so that they can be included in the `README.md`
+ [x] Setup CI/CD (run the tests) on **GitHub Actions**: https://github.com/dwyl/flutter-counter-example/issues/6

Remember the purpose of this example is to give people a beginner-friendly intro to `Flutter` so that they can _eventually_ contribute to our **`App`**. So removing all barriers is _essential_! 🙏

**Comment by LuchoTurtle** [comment]
In the https://github.com/dwyl/flutter-counter-example/pull/7, this part should be done. I'm off to tackle the Github Actions part :)

**Comment by nelsonic** [comment]
@LuchoTurtle please upload the photos/videos to GitHub which you can then display in the `README.md` 📸

**Comment by LuchoTurtle** [comment]
I don't currently have anything to take a photo of the phone itself so I just recorded a video. This is on the readme. 

https://user-images.githubusercontent.com/17494745/201970936-f4163aec-d9f1-4270-b8a6-b64b5a4c7e69.mp4

**Comment by nelsonic** [comment]
Nice one. Looking good. 👌

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/flutter-counter-example/pull/7 👌
